"""Connected, crease-aligned raised ground. Run in Blender through MCP.
The evaluated Blender triangles are the single source for render/collision/height.
Coordinates below are Unity x, height above meadow, rearward distance.
"""
import bpy, json
from pathlib import Path
ROOT=Path('/Users/kevinandersson/Desktop/SeaSick')
foot=[(-78,15),(-52,-2),(-18,6),(15,3),(52,-4),(78,20),(79,48),(52,73),(12,82),(-27,77),(-65,61),(-80,40)]
crest=[(-65,26,20),(-47,21,10),(-17,18,34),(13,20,33),(45,27,7),(64,32,24),(63,31,44),(45,28,59),(9,34,67),(-23,30,62),(-52,26,50),(-66,28,37)]
# Heights in the design are absolute relative to the 5.2 m meadow.
verts=[(x,-.35,z) for x,z in foot]
# An uneven shoulder is part of the wall topology, not an attached object.
# Its varying elevation prevents a horizontal masonry course; the main lower
# faces remain broad, with small upper facets turning into the turf ridge.
shoulder=[.70,.48,.55,.55,.68,.82,.54,.75,.46,.79,.57,.81]
for i,((fx,fz),(cx,ch,cz)) in enumerate(zip(foot,crest)):
    t=shoulder[i]
    # Stay on the ramp's original supporting plane.
    bulge=0 if i in (1,2,3,4) else .15
    verts.append((fx+(cx-fx)*(t-bulge),-.35+(ch-5.2+.35)*t,fz+(cz-fz)*(t-bulge)))
verts += [(x,h-5.2,z) for x,h,z in crest]
inner=[(x*.56,h-5.2,49+(z-49)*.48) for x,h,z in crest]
verts+=inner
upper=[(x*.73,52+(z-52)*.68) for x,h,z in inner]
verts += [(x,36+.28*x+.14*(z-52)-5.2,z) for x,z in upper]
verts.append((0,36-5.2,52))
faces=[]; rocks=[]
for ring in range(4):
    for i in range(12):
        j=(i+1)%12;a=ring*12+i;b=ring*12+j;c=b+12;d=a+12
        # Explicit broad facets, no subdivision/no displaced heightfield.
        faces += [(a,b,c),(a,c,d)]
        rocks += [ring in (0,1,3) and i not in (1,2,3)]*2
for i in range(12): faces.append((48+i,48+(i+1)%12,60));rocks.append(False)
previous=bpy.context.window.scene
scene=bpy.data.scenes.get('Authored_Home_Plateau') or bpy.data.scenes.new('Authored_Home_Plateau')
for ob in list(scene.objects): bpy.data.objects.remove(ob,do_unlink=True)
bpy.context.window.scene=scene
mesh=bpy.data.meshes.new('Connected_Plateau_Surface')
# Blender x/y ground, z up; faces CCW in ground coordinates.
mesh.from_pydata([(x,z,h) for x,h,z in verts],[],faces);mesh.update()
ob=bpy.data.objects.new('Home_Plateau_Connected_Ground',mesh);scene.collection.objects.link(ob)
attr=mesh.color_attributes.new(name='Color',type='FLOAT_COLOR',domain='CORNER')
for p,rock in zip(mesh.polygons,rocks):
    p.use_smooth=False
    rock = p.normal.z < .78
    rocks[p.index] = rock
    color=(.43,.40,.33,1) if rock else (.100,.243,.030,1)
    for li in p.loop_indices:attr.data[li].color=color
# Serialize evaluated source triangles, preserving authored crease boundaries.
mesh.calc_loop_triangles()
v=[(round(p.co.x,5),round(p.co.z,5),round(p.co.y,5)) for p in mesh.vertices]
t=[tuple(t.vertices) for t in mesh.loop_triangles]
r=[rocks[t.polygon_index] for t in mesh.loop_triangles]
out=ROOT/'tools/blender/source';out.mkdir(exist_ok=True)
(out/'home-plateau.json').write_text(json.dumps({'vertices':v,'triangles':t,'rock':r},indent=2)+'\n')
bpy.data.libraries.write(str(out/'home-plateau.blend'),{scene})
# C# constant switches remain compatible with Burst; no mutable global tables.
cs=['// Generated by tools/blender/home_plateau.py through Blender MCP. Do not hand edit.','using Unity.Mathematics;','namespace SeaSick.Terrain {','public static class HomePlateauData {',f'public const int VertexCount={len(v)}, TriangleCount={len(t)};','public static float3 Vertex(int i) { switch(i) {']
for i,p in enumerate(v):cs.append(f'case {i}: return new float3({p[0]}f,{p[1]}f,{p[2]}f);')
cs += ['default: return float3.zero; }}','public static int3 Triangle(int i) { switch(i) {']
# Reverse winding when swapping Blender Y/Z into Unity coordinates.
for i,(a,b,c) in enumerate(t):cs.append(f'case {i}: return new int3({a},{c},{b});')
cs += ['default: return int3.zero; }}','public static bool IsRock(int i) { switch(i) {']
cs += [f'case {i}:' for i,x in enumerate(r) if x]
cs += ['return true; default: return false; }}','}}']
(ROOT/'Assets/_Project/Scripts/Terrain/HomePlateauData.cs').write_text('\n'.join(cs)+'\n')
bpy.context.window.scene=previous
print(f'Authored connected ground: {len(v)} vertices, {len(t)} triangles, {sum(r)} rock facets. Original scene restored.')
